
FROM node:22.10.0

RUN npm i -g pnpm@9.14.4

WORKDIR /app

COPY ./package.json ./.npmrc ./

RUN pnpm i --ignore-scripts

COPY ./tsconfig.base.json ./
COPY ./ ./

RUN pnpm build

CMD ["pnpm", "start:prod"]