
FROM node:20.18.0

RUN npm i -g pnpm@9.12.3

WORKDIR /app

COPY ./package.json ./.npmrc ./

RUN pnpm i --ignore-scripts

COPY ./tsconfig.base.json ./
COPY ./ ./

RUN pnpm build

CMD ["pnpm", "start:prod"]